spring.application.name=scm2.0
server.port=8081

# mysql database configuration
# data source url
spring.datasource.url=jdbc:mysql://localhost:3309/scm2
spring.datasource.username=root
spring.datasource.password=admin

#jpa configurations
spring.jpa.show-sql=true

#for creating schemas and tables
spring.jpa.hibernate.ddl-auto=update
#email configuration

# security configuration 

#spring.security.user.name=durgesh
#spring.security.user.password=durgesh

# oauth2 client configuration

#google configure
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=125323130822-cm2mmckl0gi98b1dtpdhh93vd1r3en2b.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile

# github configure

# facebook configure

